config/routes.rb
Autocomplete::Application.routes.draw do
  resources :search_suggestions

  resources :products
  root to: 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base

  def self.search(term)
  	where("name like :term or category like :term", term: "%#{term}%")
  end	
end

app/models/search_suggestion.rb
class SearchSuggestion < ActiveRecord::Base
  
  def self.terms_for(prefix)
  	$redis.zrevrange "search-suggestions:#{prefix.downcase}", 0, 9  
  end

  def self.index_products
    Product.find_each do |product|
      index_term(product.name)
      product.name.split.each { |t| index_term(t) }
      index_term(product.category)
    end
  end
 
  def self.index_term(term)
    1.upto(term.length - 1) do |n|
      prefix = term[0, n]
      $redis.zincrby "search-suggestions:#{prefix.downcase}", 1, term.downcase
    end  
  end     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def index
  	@products = Product.search(params[:search])
  end

  private

  def product_params
  	params.require(:product).permit(:name, :category, :price)
  end	
end

app/controllers/search_suggestions_controller.rb
class SearchSuggestionsController < ApplicationController
  def index
  	render json: SearchSuggestion.terms_for(params[:term])
  end

  private

  def search_suggestion_params
  	params.require(:search_suggestion).permit(:term, :popularity)
  end		
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/search_suggestions_helper.rb
module SearchSuggestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Autocomplete</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
</body>
</html>

app/views/products/index.html.erb
<h1>Products</h1>

<%= form_tag products_path, method: :get do %>
  <%= text_field_tag :search, params[:search], size: 30 %>
  <%= submit_tag "Search", name: nil %>
<% end %>

<% @products.each do |product| %>
  <h2><%= product.name %></h2>
  Price: <%= number_to_currency product.price %> |
  Category: <%= product.category %>
<% end %>    